// GENERATED by scripts/generate-migrations.ts — do not edit by hand.
// Regenerate with `bun run migrations:generate`; CI enforces `bun run migrations:check`.
import type { WorldMigrationStep } from '@openqueue/core/world';

export const migrations: readonly WorldMigrationStep[] = [
  {
    id: '0001_init',
    checksum:
      '857815eaff72011cc3533122d43c97a11d7461c3cee1530a4b2381d035d9f8e3',
    sql: `CREATE TABLE "openqueue"."alert_channels" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"preset" text NOT NULL,
	"url" text NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"display_name" text,
	"icon_url" text,
	"headers" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE "openqueue"."alert_rules" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"trigger" text NOT NULL,
	"severity" text NOT NULL,
	"queues" text[] DEFAULT '{}' NOT NULL,
	"job_names" text[] DEFAULT '{}' NOT NULL,
	"threshold" integer,
	"contact_point_ids" text[] DEFAULT '{}' NOT NULL,
	"cooldown_ms" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE "openqueue"."jobs" (
	"namespace" text NOT NULL,
	"queue" text NOT NULL,
	"id" text NOT NULL,
	"name" text NOT NULL,
	"data" jsonb,
	"priority" integer DEFAULT 0 NOT NULL,
	"attempts" integer DEFAULT 1 NOT NULL,
	"attempts_made" integer DEFAULT 0 NOT NULL,
	"backoff" jsonb,
	"state" text DEFAULT 'waiting' NOT NULL,
	"run_at" timestamp with time zone DEFAULT now() NOT NULL,
	"claimed_until" timestamp with time zone,
	"stalled_count" integer DEFAULT 0 NOT NULL,
	"seq" bigint GENERATED ALWAYS AS IDENTITY (sequence name "openqueue"."jobs_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"processed_on" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "jobs_pk" PRIMARY KEY("namespace","queue","id")
);
CREATE TABLE "openqueue"."catalog" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"queue" text NOT NULL,
	"attempts" integer NOT NULL,
	"backoff" jsonb NOT NULL,
	"concurrency" integer NOT NULL,
	"ttl" integer,
	"max_stalled_count" integer,
	"cron" text,
	"tags" text[] DEFAULT '{}' NOT NULL,
	"description" text,
	"schema" jsonb,
	"updated_at" timestamp with time zone NOT NULL,
	"version" text NOT NULL
);
CREATE TABLE "openqueue"."run_events" (
	"id" text PRIMARY KEY NOT NULL,
	"run_id" text NOT NULL,
	"type" text NOT NULL,
	"data" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE "openqueue"."run_spans" (
	"id" text PRIMARY KEY NOT NULL,
	"run_id" text NOT NULL,
	"attempt" integer NOT NULL,
	"trace_id" text NOT NULL,
	"span_id" text NOT NULL,
	"parent_span_id" text,
	"kind" text NOT NULL,
	"name" text NOT NULL,
	"level" text,
	"status" text,
	"error" jsonb,
	"started_at" timestamp with time zone NOT NULL,
	"duration_ms" integer,
	"attributes" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE "openqueue"."runs" (
	"id" text PRIMARY KEY NOT NULL,
	"transport_job_id" text,
	"task" text NOT NULL,
	"queue" text NOT NULL,
	"status" text NOT NULL,
	"input" jsonb,
	"output" jsonb,
	"error" jsonb,
	"meta" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"tags" text[] DEFAULT '{}' NOT NULL,
	"schedule_id" text,
	"schedule_external_id" text,
	"created_at" timestamp with time zone NOT NULL,
	"started_at" timestamp with time zone,
	"finished_at" timestamp with time zone,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE "openqueue"."schedule_instances" (
	"id" text PRIMARY KEY NOT NULL,
	"schedule_id" text NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"next_run_at" timestamp with time zone,
	"last_run_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE "openqueue"."schedules" (
	"id" text PRIMARY KEY NOT NULL,
	"task" text NOT NULL,
	"type" text DEFAULT 'IMPERATIVE' NOT NULL,
	"input" jsonb,
	"active" boolean DEFAULT true NOT NULL,
	"cron" text NOT NULL,
	"timezone" text DEFAULT 'UTC' NOT NULL,
	"external_id" text,
	"deduplication_key" text,
	"meta" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"next_run_at" timestamp with time zone,
	"last_run_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE "openqueue"."run_events" ADD CONSTRAINT "run_events_run_id_runs_id_fk" FOREIGN KEY ("run_id") REFERENCES "openqueue"."runs"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "openqueue"."run_spans" ADD CONSTRAINT "run_spans_run_id_runs_id_fk" FOREIGN KEY ("run_id") REFERENCES "openqueue"."runs"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "openqueue"."schedule_instances" ADD CONSTRAINT "schedule_instances_schedule_id_schedules_id_fk" FOREIGN KEY ("schedule_id") REFERENCES "openqueue"."schedules"("id") ON DELETE cascade ON UPDATE no action;
CREATE INDEX "openqueue_jobs_claim_idx" ON "openqueue"."jobs" USING btree ("namespace","queue","state","run_at","priority","seq");
CREATE INDEX "queue_catalog_queue_idx" ON "openqueue"."catalog" USING btree ("queue");
CREATE INDEX "queue_catalog_updated_at_idx" ON "openqueue"."catalog" USING btree ("updated_at");
CREATE INDEX "queue_run_events_run_id_idx" ON "openqueue"."run_events" USING btree ("run_id");
CREATE INDEX "queue_run_events_created_at_idx" ON "openqueue"."run_events" USING btree ("created_at");
CREATE INDEX "queue_run_spans_run_id_idx" ON "openqueue"."run_spans" USING btree ("run_id");
CREATE INDEX "queue_runs_task_idx" ON "openqueue"."runs" USING btree ("task");
CREATE INDEX "queue_runs_transport_job_id_idx" ON "openqueue"."runs" USING btree ("transport_job_id");
CREATE INDEX "queue_runs_status_idx" ON "openqueue"."runs" USING btree ("status");
CREATE INDEX "queue_runs_created_at_idx" ON "openqueue"."runs" USING btree ("created_at");
CREATE INDEX "queue_runs_meta_idx" ON "openqueue"."runs" USING gin ("meta");
CREATE INDEX "queue_runs_tags_idx" ON "openqueue"."runs" USING gin ("tags");
CREATE INDEX "queue_runs_schedule_id_idx" ON "openqueue"."runs" USING btree ("schedule_id");
CREATE INDEX "queue_runs_schedule_external_id_idx" ON "openqueue"."runs" USING btree ("schedule_external_id");
CREATE INDEX "queue_schedule_instances_schedule_id_idx" ON "openqueue"."schedule_instances" USING btree ("schedule_id");
CREATE INDEX "queue_schedule_instances_next_run_at_idx" ON "openqueue"."schedule_instances" USING btree ("next_run_at");
CREATE UNIQUE INDEX "queue_schedule_instances_schedule_id_unique" ON "openqueue"."schedule_instances" USING btree ("schedule_id");
CREATE INDEX "queue_schedules_task_idx" ON "openqueue"."schedules" USING btree ("task");
CREATE INDEX "queue_schedules_external_id_idx" ON "openqueue"."schedules" USING btree ("external_id");
CREATE INDEX "queue_schedules_next_run_at_idx" ON "openqueue"."schedules" USING btree ("next_run_at");
CREATE UNIQUE INDEX "queue_schedules_deduplication_key_idx" ON "openqueue"."schedules" USING btree ("deduplication_key") WHERE "openqueue"."schedules"."deduplication_key" IS NOT NULL;
`,
  },
  {
    id: '0002_init',
    checksum:
      'a487f14278a33be4e659bd8392f4c8ed2739bad936cd716ed7028f592e8c7146',
    sql: `ALTER TABLE "openqueue"."jobs" ADD COLUMN "claim_id" text;
`,
  },
];
