#!/usr/bin/env bun

import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import {
  cpSync,
  existsSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

/**
 * Generate (and, with `--check`, verify) the committed `src/migrations.ts` from
 * `src/schema.ts` via drizzle-kit. drizzle-kit owns the diff; this script only
 * normalizes its output into embeddable migration steps:
 *   - strip drizzle's `--> statement-breakpoint` markers (we run each step's SQL
 *     as one multi-statement query, not split on breakpoints);
 *   - rewrite `CREATE SCHEMA "openqueue"` to `IF NOT EXISTS` (the runner
 *     pre-creates the schema for its bookkeeping table);
 *   - sha256 the normalized SQL (generator-time) as the step checksum;
 *   - re-number to 1-based `0001_<name>` ids.
 *
 * `--check` (CI): (1) regenerate into a scratch seeded with the committed
 * `drizzle/` — a new file means schema.ts drifted from a committed migration;
 * (2) recompute the steps and compare to the committed `src/migrations.ts`.
 */

const packageRoot = fileURLToPath(new URL('..', import.meta.url));
const drizzleDir = join(packageRoot, 'drizzle');
const migrationsFile = join(packageRoot, 'src', 'migrations.ts');
const check = process.argv.includes('--check');

interface GeneratedStep {
  id: string;
  checksum: string;
  sql: string;
}

interface Journal {
  entries: { idx: number; tag: string }[];
}

function normalizeSql(raw: string): string {
  const withoutBreakpoints = raw.replace(/\s*-->\s*statement-breakpoint/g, '');
  return `${withoutBreakpoints
    .replace(
      /CREATE SCHEMA "openqueue";/g,
      'CREATE SCHEMA IF NOT EXISTS "openqueue";',
    )
    .trim()}\n`;
}

function readSteps(dir: string): GeneratedStep[] {
  const journal = JSON.parse(
    readFileSync(join(dir, 'meta', '_journal.json'), 'utf8'),
  ) as Journal;
  const ordered = [...journal.entries].sort((a, b) => a.idx - b.idx);
  return ordered.map((entry, i) => {
    const sql = normalizeSql(
      readFileSync(join(dir, `${entry.tag}.sql`), 'utf8'),
    );
    const checksum = createHash('sha256').update(sql).digest('hex');
    const name = entry.tag.replace(/^\d+_/, '');
    const id = `${String(i + 1).padStart(4, '0')}_${name}`;
    return { id, checksum, sql };
  });
}

function sqlLiteral(value: string): string {
  const escaped = value
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${');
  return `\`${escaped}\``;
}

function emit(steps: GeneratedStep[]): string {
  const body = steps
    .map(
      (step) =>
        `  {\n    id: '${step.id}',\n    checksum: '${step.checksum}',\n    sql: ${sqlLiteral(step.sql)},\n  },`,
    )
    .join('\n');
  return `// GENERATED by scripts/generate-migrations.ts — do not edit by hand.
// Regenerate with \`bun run migrations:generate\`; CI enforces \`bun run migrations:check\`.
import type { WorldMigrationStep } from '@openqueue/core/world';

export const migrations: readonly WorldMigrationStep[] = [
${body}
];
`;
}

/**
 * `out` must stay relative to the package root: drizzle-kit joins it onto `./`
 * internally, so an absolute path can't find its own snapshot to diff against.
 * The default config `out` ('./drizzle') is used when `relativeOut` is omitted.
 */
function runGenerate(
  relativeOut: string | undefined,
  allowPrompts: boolean,
): void {
  const env = { ...process.env };
  if (relativeOut !== undefined) env.MIGRATIONS_OUT = relativeOut;
  execFileSync('bun', ['x', 'drizzle-kit', 'generate', '--name', 'init'], {
    cwd: packageRoot,
    env,
    stdio: [allowPrompts ? 'inherit' : 'ignore', 'inherit', 'inherit'],
  });
}

function countSqlFiles(dir: string): number {
  return readdirSync(dir).filter((file) => /^\d+_.*\.sql$/.test(file)).length;
}

async function committedSteps(): Promise<GeneratedStep[]> {
  const mod = (await import(pathToFileURL(migrationsFile).href)) as {
    migrations: GeneratedStep[];
  };
  return mod.migrations;
}

if (check) {
  if (!existsSync(migrationsFile)) {
    console.error(
      '[migrations:check] src/migrations.ts is missing. Run `bun run migrations:generate`.',
    );
    process.exit(1);
  }

  // Scratch lives under node_modules (gitignored) and is addressed relatively so
  // drizzle-kit can read its snapshot — see runGenerate.
  const relativeScratch = join('node_modules', '.oq-migrations-check');
  const scratchDrizzle = join(packageRoot, relativeScratch);
  rmSync(scratchDrizzle, { recursive: true, force: true });
  try {
    cpSync(drizzleDir, scratchDrizzle, { recursive: true });
    const before = countSqlFiles(scratchDrizzle);
    try {
      runGenerate(relativeScratch, false);
    } catch {
      console.error(
        '[migrations:check] drizzle-kit generate failed (schema drift needs a rename decision?). Run `bun run migrations:generate`.',
      );
      process.exit(1);
    }
    if (countSqlFiles(scratchDrizzle) !== before) {
      console.error(
        '[migrations:check] schema drift — src/schema.ts changed without a committed migration. Run `bun run migrations:generate`.',
      );
      process.exit(1);
    }

    const expected = readSteps(drizzleDir);
    const actual = await committedSteps();
    const drift =
      expected.length !== actual.length ||
      expected.some((step, i) => {
        const other = actual[i];
        return (
          !other ||
          other.id !== step.id ||
          other.checksum !== step.checksum ||
          other.sql !== step.sql
        );
      });
    if (drift) {
      console.error(
        '[migrations:check] src/migrations.ts is out of date. Run `bun run migrations:generate`.',
      );
      process.exit(1);
    }

    console.log('[migrations:check] clean');
  } finally {
    rmSync(scratchDrizzle, { recursive: true, force: true });
  }
} else {
  runGenerate(undefined, true);
  const steps = readSteps(drizzleDir);
  writeFileSync(migrationsFile, emit(steps));
  console.log(`[migrations:generate] wrote ${steps.length} step(s):`);
  for (const step of steps) console.log(`  ${step.id}  ${step.checksum}`);
}
